services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: pgcontrolF
      POSTGRES_PASSWORD: controlF
      POSTGRES_DB: controlf
    ports:
      - "7001:5432"
